amcl:
  ros__parameters:
    use_sim_time: True
    # ... AMCL settings ...

bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    default_bt_xml_filename: "navigate_to_pose_w_replanning_and_recovery.xml"

controller_server:
  ros__parameters:
    use_sim_time: True
    # Define the robot shape (Polygon)
    # Example: A rectangle 0.5m wide, 0.3m deep
    footprint: "[ [0.15, 0.25], [0.15, -0.25], [-0.15, -0.25], [-0.15, 0.25] ]"
    controller_plugins: ["FollowPath"]

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: odom
      plugin_names: ["obstacle_layer", "inflation_layer"]
      inflation_layer:
        # Inflate obstacles by 0.55m (radius + safety)
        inflation_radius: 0.55 
